version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fit_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis

  app:
    build: .
    container_name: fit-backend
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://postgres:5432/fit_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      APP_JWT_SECRET: 8g884e7VfB5CLneukGSmREnYowm6jyvTsBmcbAXm2UgBituYoBVcC1FEISw0439o/FZseqhXJRGxuzWO7X4ogw==
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME:-thinhndde170386@fpt.edu.vn}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD:-drps xxtq wdmh vqnr}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-dvc9igofd}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-151465277544439}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-1BtxoQ-JhCpsTSI5BDJgXGdZtKs}
      STRIPE_API_KEY: ${STRIPE_API_KEY:-sk_test_your_stripe_secret_key}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-whsec_sCYVgfRcb7DwG6KPTJCiUqrSwrRthfZF}

volumes:
  pg-data:
  redis-data:
