--
-- PostgreSQL database dump
--

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg12+1)
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it



--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS '';


--
-- Name: hstore; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;


--
-- Name: EXTENSION hstore; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION hstore IS 'data type for storing sets of (key, value) pairs';


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.addresses (
    id bigint NOT NULL,
    city character varying(255),
    country_code character varying(3),
    created_at timestamp(6) without time zone NOT NULL,
    district_id integer,
    district_name character varying(255),
    full_name character varying(255) NOT NULL,
    is_default boolean,
    line character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    province_id integer,
    updated_at timestamp(6) without time zone,
    ward character varying(255),
    ward_code character varying(20),
    user_id bigint NOT NULL
);



--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart_details (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    quantity integer NOT NULL,
    updated_at timestamp without time zone DEFAULT now(),
    detail_id bigint NOT NULL,
    user_id bigint NOT NULL
);



--
-- Name: cart_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_active boolean NOT NULL,
    name text NOT NULL,
    slug character varying(255) NOT NULL,
    parent_id bigint
);



--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: colors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.colors (
    id smallint NOT NULL,
    hex character varying(7),
    is_active boolean DEFAULT true NOT NULL,
    name text NOT NULL
);



--
-- Name: colors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.colors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.colors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.images (
    id bigint NOT NULL,
    alt text,
    created_at timestamp(6) without time zone,
    url text NOT NULL
);



--
-- Name: images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interactions (
    id bigint NOT NULL,
    action_type character varying(20) NOT NULL,
    count integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);



--
-- Name: interactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.interactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_detail_promotions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_detail_promotions (
    discount_amount numeric(12,2) NOT NULL,
    promotion_name text,
    detail_id bigint NOT NULL,
    order_id bigint NOT NULL,
    promotion_id bigint
);



--
-- Name: order_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_details (
    id bigint NOT NULL,
    color_label text,
    promotion_id bigint,
    quantity integer NOT NULL,
    size_label text,
    title text NOT NULL,
    total_price numeric(12,2),
    unit_price numeric(12,2) NOT NULL,
    order_id bigint NOT NULL,
    detail_id bigint NOT NULL
);



--
-- Name: order_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(3) NOT NULL,
    discount_amount numeric(12,2) NOT NULL,
    note text,
    payment_status character varying(255) NOT NULL,
    shipping_fee numeric(12,2) NOT NULL,
    status character varying(255) NOT NULL,
    subtotal_amount numeric(12,2) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    updated_at timestamp(6) without time zone,
    shipping_address_id bigint NOT NULL,
    user_id bigint NOT NULL,
    voucher_id bigint,
    CONSTRAINT orders_payment_status_check CHECK (((payment_status)::text = ANY (ARRAY[('UNPAID'::character varying)::text, ('PAID'::character varying)::text, ('PARTIALLY_PAID'::character varying)::text, ('REFUNDED'::character varying)::text, ('CANCELLED'::character varying)::text]))),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY (ARRAY[('UNFULFILLED'::character varying)::text, ('FULFILLED'::character varying)::text, ('PARTIALLY_FULFILLED'::character varying)::text, ('CANCELLED'::character varying)::text])))
);



--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_token (
    id bigint NOT NULL,
    expiry_date timestamp(6) with time zone,
    token character varying(255),
    user_id bigint NOT NULL
);



--
-- Name: password_reset_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.password_reset_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    method character varying(255) NOT NULL,
    paid_at timestamp(6) without time zone,
    provider character varying(100),
    status character varying(255) NOT NULL,
    transaction_no character varying(255),
    order_id bigint NOT NULL,
    CONSTRAINT payments_method_check CHECK (((method)::text = ANY (ARRAY[('CASH_ON_DELIVERY'::character varying)::text, ('BANK_TRANSFER'::character varying)::text, ('CREDIT_CARD'::character varying)::text, ('DEBIT_CARD'::character varying)::text, ('E_WALLET'::character varying)::text, ('PAYPAL'::character varying)::text, ('MOMO'::character varying)::text, ('ZALOPAY'::character varying)::text, ('VNPAY'::character varying)::text]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY (ARRAY[('UNPAID'::character varying)::text, ('PAID'::character varying)::text, ('PARTIALLY_PAID'::character varying)::text, ('REFUNDED'::character varying)::text, ('CANCELLED'::character varying)::text])))
);



--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_categories (
    product_id bigint NOT NULL,
    category_id bigint NOT NULL
);



--
-- Name: product_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_details (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_active boolean,
    price numeric(12,2) NOT NULL,
    quantity integer,
    slug character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    color_id smallint NOT NULL,
    product_id bigint NOT NULL,
    size_id smallint NOT NULL
);



--
-- Name: product_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_images (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    detail_id bigint NOT NULL,
    image_id bigint NOT NULL
);



--
-- Name: product_images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    is_active boolean,
    title text NOT NULL,
    updated_at timestamp(6) without time zone
);



--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: promotion_targets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.promotion_targets (
    target_id bigint NOT NULL,
    target_type character varying(255) NOT NULL,
    promotion_id bigint NOT NULL,
    CONSTRAINT promotion_targets_target_type_check CHECK (((target_type)::text = ANY (ARRAY[('SKU'::character varying)::text, ('PRODUCT'::character varying)::text, ('CATEGORY'::character varying)::text])))
);



--
-- Name: promotions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.promotions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    end_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    name text NOT NULL,
    start_at timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    value numeric(12,2) NOT NULL,
    CONSTRAINT promotions_type_check CHECK (((type)::text = ANY (ARRAY[('PERCENT'::character varying)::text, ('AMOUNT'::character varying)::text])))
);



--
-- Name: promotions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.promotions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promotions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rag_documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rag_documents (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    source character varying(100),
    ref_id character varying(100),
    title character varying(500),
    content text NOT NULL,
    embedding public.vector(1536) NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);



--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    is_revoked boolean NOT NULL,
    jti uuid NOT NULL,
    revoked_at timestamp(6) without time zone,
    token_hash character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);



--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refund_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refund_images (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    image_id bigint NOT NULL,
    refund_request_id bigint NOT NULL
);



--
-- Name: refund_images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refund_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refund_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refund_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refund_requests (
    id bigint NOT NULL,
    admin_note text,
    created_at timestamp(6) without time zone NOT NULL,
    processed_at timestamp(6) without time zone,
    reason text NOT NULL,
    refund_amount numeric(12,2) NOT NULL,
    status character varying(20) NOT NULL,
    stripe_refund_id character varying(255),
    updated_at timestamp(6) without time zone,
    order_id bigint NOT NULL,
    processed_by bigint,
    user_id bigint NOT NULL,
    CONSTRAINT refund_requests_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('APPROVED'::character varying)::text, ('REJECTED'::character varying)::text, ('COMPLETED'::character varying)::text])))
);



--
-- Name: refund_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refund_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refund_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews (
    order_detail_id bigint NOT NULL,
    content text,
    created_at timestamp(6) without time zone,
    rating numeric(2,2) NOT NULL,
    id bigint NOT NULL,
    product_detail_id bigint NOT NULL,
    user_id bigint NOT NULL
);



--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    role_name character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone
);



--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shipments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shipments (
    id bigint NOT NULL,
    carrier character varying(100),
    created_at timestamp(6) without time zone NOT NULL,
    delivered_at timestamp(6) without time zone,
    shipped_at timestamp(6) without time zone,
    status character varying(255),
    tracking_no character varying(255),
    order_id bigint NOT NULL,
    CONSTRAINT shipments_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('CONFIRMED'::character varying)::text, ('PROCESSING'::character varying)::text, ('SHIPPED'::character varying)::text, ('DELIVERED'::character varying)::text, ('CANCELLED'::character varying)::text, ('RETURNED'::character varying)::text, ('REFUNDED'::character varying)::text])))
);



--
-- Name: shipments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shipments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sizes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sizes (
    id smallint NOT NULL,
    code text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    label text NOT NULL
);



--
-- Name: sizes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sizes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sizes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tracking_events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tracking_events (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    event_time timestamp(6) without time zone NOT NULL,
    location character varying(255),
    status character varying(50) NOT NULL,
    shipment_id bigint NOT NULL,
    CONSTRAINT tracking_events_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('CONFIRMED'::character varying)::text, ('PROCESSING'::character varying)::text, ('SHIPPED'::character varying)::text, ('DELIVERED'::character varying)::text, ('CANCELLED'::character varying)::text, ('RETURNED'::character varying)::text, ('REFUNDED'::character varying)::text])))
);



--
-- Name: tracking_events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tracking_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tracking_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_measurements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_measurements (
    id bigint NOT NULL,
    age integer,
    belly_shape character varying(10),
    bmi numeric(4,2) NOT NULL,
    chest numeric(5,2) NOT NULL,
    chest_shape character varying(10),
    created_at timestamp(6) without time zone NOT NULL,
    fit_preference character varying(15),
    gender character varying(10) NOT NULL,
    has_return_history boolean,
    height numeric(5,2) NOT NULL,
    hip_shape character varying(10),
    hips numeric(5,2) NOT NULL,
    updated_at timestamp(6) without time zone,
    waist numeric(5,2) NOT NULL,
    weight numeric(5,2) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_measurements_belly_shape_check CHECK (((belly_shape)::text = ANY (ARRAY[('FLAT'::character varying)::text, ('NORMAL'::character varying)::text, ('ROUND'::character varying)::text]))),
    CONSTRAINT user_measurements_chest_shape_check CHECK (((chest_shape)::text = ANY (ARRAY[('SLIM'::character varying)::text, ('NORMAL'::character varying)::text, ('BROAD'::character varying)::text]))),
    CONSTRAINT user_measurements_fit_preference_check CHECK (((fit_preference)::text = ANY (ARRAY[('TIGHT'::character varying)::text, ('COMFORTABLE'::character varying)::text, ('LOOSE'::character varying)::text]))),
    CONSTRAINT user_measurements_gender_check CHECK (((gender)::text = ANY (ARRAY[('MALE'::character varying)::text, ('FEMALE'::character varying)::text]))),
    CONSTRAINT user_measurements_hip_shape_check CHECK (((hip_shape)::text = ANY (ARRAY[('NARROW'::character varying)::text, ('NORMAL'::character varying)::text, ('WIDE'::character varying)::text])))
);



--
-- Name: user_measurements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_measurements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_measurements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_ranks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_ranks (
    id smallint NOT NULL,
    code text NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    name text NOT NULL
);



--
-- Name: user_ranks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_ranks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_ranks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);



--
-- Name: user_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar_url character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    dob date,
    email character varying(255) NOT NULL,
    email_verified boolean NOT NULL,
    is_active boolean NOT NULL,
    last_login_at timestamp(6) without time zone,
    password character varying(255) NOT NULL,
    phone character varying(15),
    phone_verified boolean NOT NULL,
    rank_id smallint,
    reason character varying(500),
    reset_password_token character varying(255),
    reset_password_expires_at timestamp(6) without time zone,
    total_spent numeric(12,2),
    updated_at timestamp(6) without time zone,
    username character varying(50) NOT NULL
);



--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vector_store; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vector_store (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    content text,
    metadata json,
    embedding public.vector(1536)
);



--
-- Name: voucher_rank_rules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.voucher_rank_rules (
    id bigint NOT NULL,
    rank_id smallint NOT NULL,
    voucher_id bigint NOT NULL
);



--
-- Name: voucher_rank_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.voucher_rank_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voucher_rank_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: voucher_usages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.voucher_usages (
    id bigint NOT NULL,
    discount_amount numeric(12,2),
    status character varying(255) NOT NULL,
    used_at timestamp(6) without time zone,
    order_id bigint,
    user_id bigint NOT NULL,
    voucher_id bigint NOT NULL,
    CONSTRAINT voucher_usages_status_check CHECK (((status)::text = ANY (ARRAY[('APPLIED'::character varying)::text, ('CANCELLED'::character varying)::text, ('RESERVED'::character varying)::text])))
);



--
-- Name: voucher_usages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.voucher_usages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voucher_usages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vouchers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vouchers (
    id bigint NOT NULL,
    audience_type character varying(255) NOT NULL,
    code character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    end_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    max_discount numeric(12,2),
    min_order_amount numeric(12,2),
    name text NOT NULL,
    start_at timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    usage_limit_per_user integer,
    usage_limit_total integer,
    value numeric(12,2) NOT NULL,
    CONSTRAINT vouchers_audience_type_check CHECK (((audience_type)::text = ANY (ARRAY[('ALL'::character varying)::text, ('RANK'::character varying)::text]))),
    CONSTRAINT vouchers_type_check CHECK (((type)::text = ANY (ARRAY[('PERCENT'::character varying)::text, ('FIXED'::character varying)::text])))
);



--
-- Name: vouchers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vouchers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vouchers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wishlists (
    wishlist_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    detail_id bigint NOT NULL,
    user_id bigint NOT NULL
);



--
-- Name: wishlists_wishlist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wishlists ALTER COLUMN wishlist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlists_wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- Name: cart_details cart_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_details
    ADD CONSTRAINT cart_details_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: colors colors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.colors
    ADD CONSTRAINT colors_pkey PRIMARY KEY (id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: roles idx_role_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT idx_role_name UNIQUE (role_name);


--
-- Name: users idx_user_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT idx_user_email UNIQUE (email);


--
-- Name: user_ranks idx_user_rank_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_ranks
    ADD CONSTRAINT idx_user_rank_code UNIQUE (code);


--
-- Name: users idx_user_username; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT idx_user_username UNIQUE (username);


--
-- Name: vouchers idx_voucher_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT idx_voucher_code UNIQUE (code);


--
-- Name: images images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);


--
-- Name: interactions interactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interactions
    ADD CONSTRAINT interactions_pkey PRIMARY KEY (id);


--
-- Name: order_detail_promotions order_detail_promotions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_detail_promotions
    ADD CONSTRAINT order_detail_promotions_pkey PRIMARY KEY (detail_id, order_id);


--
-- Name: order_details order_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: password_reset_token password_reset_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT password_reset_token_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: product_categories product_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_pkey PRIMARY KEY (product_id, category_id);


--
-- Name: product_details product_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_details
    ADD CONSTRAINT product_details_pkey PRIMARY KEY (id);


--
-- Name: product_images product_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: promotion_targets promotion_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promotion_targets
    ADD CONSTRAINT promotion_targets_pkey PRIMARY KEY (promotion_id, target_id, target_type);


--
-- Name: promotions promotions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT promotions_pkey PRIMARY KEY (id);


--
-- Name: rag_documents rag_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rag_documents
    ADD CONSTRAINT rag_documents_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: refund_images refund_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_images
    ADD CONSTRAINT refund_images_pkey PRIMARY KEY (id);


--
-- Name: refund_requests refund_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT refund_requests_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (order_detail_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: shipments shipments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT shipments_pkey PRIMARY KEY (id);


--
-- Name: sizes sizes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sizes
    ADD CONSTRAINT sizes_pkey PRIMARY KEY (id);


--
-- Name: tracking_events tracking_events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tracking_events
    ADD CONSTRAINT tracking_events_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens uk18kw8ppjw4gmmgdns9ecyg17b; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uk18kw8ppjw4gmmgdns9ecyg17b UNIQUE (jti);


--
-- Name: product_details uk4ntbp6csjyqbn2q34gdo4gie2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_details
    ADD CONSTRAINT uk4ntbp6csjyqbn2q34gdo4gie2 UNIQUE (slug);


--
-- Name: cart_details uk_cart_user_detail; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_details
    ADD CONSTRAINT uk_cart_user_detail UNIQUE (user_id, detail_id);


--
-- Name: promotions uk_promotion_name_period; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT uk_promotion_name_period UNIQUE (name, start_at, end_at);


--
-- Name: user_roles uk_user_role; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT uk_user_role UNIQUE (user_id, role_id);


--
-- Name: voucher_rank_rules uk_voucher_rank_rule; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_rank_rules
    ADD CONSTRAINT uk_voucher_rank_rule UNIQUE (voucher_id, rank_id);


--
-- Name: voucher_usages uk_voucher_usage_order; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_usages
    ADD CONSTRAINT uk_voucher_usage_order UNIQUE (order_id);


--
-- Name: user_measurements ukci82fxcvhh6qa4mh98k4xuyaj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_measurements
    ADD CONSTRAINT ukci82fxcvhh6qa4mh98k4xuyaj UNIQUE (user_id);


--
-- Name: password_reset_token ukf90ivichjaokvmovxpnlm5nin; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT ukf90ivichjaokvmovxpnlm5nin UNIQUE (user_id);


--
-- Name: wishlists ukl6wwbt2ecp6fl915j0m39a8t1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT ukl6wwbt2ecp6fl915j0m39a8t1 UNIQUE (user_id, detail_id);


--
-- Name: reviews ukmqxbtlowq75i6qkbhkod7nx84; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT ukmqxbtlowq75i6qkbhkod7nx84 UNIQUE (user_id, product_detail_id);


--
-- Name: categories ukoul14ho7bctbefv8jywp5v3i2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukoul14ho7bctbefv8jywp5v3i2 UNIQUE (slug);


--
-- Name: product_details ukqon5upttjrj500f76wrghguio; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_details
    ADD CONSTRAINT ukqon5upttjrj500f76wrghguio UNIQUE (product_id, color_id, size_id);


--
-- Name: sizes uktiy1btcyx8sbf9s1fsa9xeg16; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sizes
    ADD CONSTRAINT uktiy1btcyx8sbf9s1fsa9xeg16 UNIQUE (code);


--
-- Name: interactions unique_user_product_action; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interactions
    ADD CONSTRAINT unique_user_product_action UNIQUE (user_id, product_id, action_type);


--
-- Name: user_measurements user_measurements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_measurements
    ADD CONSTRAINT user_measurements_pkey PRIMARY KEY (id);


--
-- Name: user_ranks user_ranks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_ranks
    ADD CONSTRAINT user_ranks_pkey PRIMARY KEY (id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vector_store vector_store_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vector_store
    ADD CONSTRAINT vector_store_pkey PRIMARY KEY (id);


--
-- Name: voucher_rank_rules voucher_rank_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_rank_rules
    ADD CONSTRAINT voucher_rank_rules_pkey PRIMARY KEY (id);


--
-- Name: voucher_usages voucher_usages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_usages
    ADD CONSTRAINT voucher_usages_pkey PRIMARY KEY (id);


--
-- Name: vouchers vouchers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT vouchers_pkey PRIMARY KEY (id);


--
-- Name: wishlists wishlists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT wishlists_pkey PRIMARY KEY (wishlist_id);


--
-- Name: idx_categories_is_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_categories_is_active ON public.categories USING btree (is_active);


--
-- Name: idx_categories_parent_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_categories_parent_id ON public.categories USING btree (parent_id);


--
-- Name: idx_categories_slug; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_categories_slug ON public.categories USING btree (slug);


--
-- Name: idx_colors_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_colors_name ON public.colors USING btree (name);


--
-- Name: idx_interaction_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_interaction_created_at ON public.interactions USING btree (created_at);


--
-- Name: idx_interaction_user_product; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_interaction_user_product ON public.interactions USING btree (user_id, product_id);


--
-- Name: idx_odp_promotion_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_odp_promotion_id ON public.order_detail_promotions USING btree (promotion_id);


--
-- Name: idx_order_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_created_at ON public.orders USING btree (created_at);


--
-- Name: idx_order_details_detail_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_details_detail_id ON public.order_details USING btree (detail_id);


--
-- Name: idx_order_payment_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_payment_status ON public.orders USING btree (payment_status);


--
-- Name: idx_order_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_status ON public.orders USING btree (status);


--
-- Name: idx_order_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_user_id ON public.orders USING btree (user_id);


--
-- Name: idx_payment_order_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_payment_order_id ON public.payments USING btree (order_id);


--
-- Name: idx_product_categories_category_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_categories_category_id ON public.product_categories USING btree (category_id);


--
-- Name: idx_product_categories_product_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_categories_product_id ON public.product_categories USING btree (product_id);


--
-- Name: idx_product_details_color_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_details_color_id ON public.product_details USING btree (color_id);


--
-- Name: idx_product_details_is_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_details_is_active ON public.product_details USING btree (is_active);


--
-- Name: idx_product_details_product_color; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_details_product_color ON public.product_details USING btree (product_id, color_id);


--
-- Name: idx_product_details_product_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_details_product_id ON public.product_details USING btree (product_id);


--
-- Name: idx_product_details_size_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_details_size_id ON public.product_details USING btree (size_id);


--
-- Name: idx_product_images_detail_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_images_detail_created ON public.product_images USING btree (detail_id, created_at);


--
-- Name: idx_product_images_detail_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_images_detail_id ON public.product_images USING btree (detail_id);


--
-- Name: idx_products_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_products_created_at ON public.products USING btree (created_at DESC);


--
-- Name: idx_products_is_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_products_is_active ON public.products USING btree (is_active);


--
-- Name: idx_promotion_active_period; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_promotion_active_period ON public.promotions USING btree (is_active, start_at, end_at);


--
-- Name: idx_promotion_targets_by_promotion; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_promotion_targets_by_promotion ON public.promotion_targets USING btree (promotion_id);


--
-- Name: idx_promotion_targets_composite; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_promotion_targets_composite ON public.promotion_targets USING btree (promotion_id, target_type, target_id);


--
-- Name: idx_promotion_targets_match; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_promotion_targets_match ON public.promotion_targets USING btree (target_type, target_id);


--
-- Name: idx_promotion_targets_target; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_promotion_targets_target ON public.promotion_targets USING btree (target_type, target_id);


--
-- Name: idx_promotions_active_dates; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_promotions_active_dates ON public.promotions USING btree (is_active, start_at, end_at);


--
-- Name: idx_rag_documents_embedding; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_rag_documents_embedding ON public.rag_documents USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: idx_rag_documents_ref; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_rag_documents_ref ON public.rag_documents USING btree (source, ref_id);


--
-- Name: idx_refund_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_refund_created_at ON public.refund_requests USING btree (created_at);


--
-- Name: idx_refund_image_refund_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_refund_image_refund_id ON public.refund_images USING btree (refund_request_id);


--
-- Name: idx_refund_order_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_refund_order_id ON public.refund_requests USING btree (order_id);


--
-- Name: idx_refund_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_refund_status ON public.refund_requests USING btree (status);


--
-- Name: idx_refund_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_refund_user_id ON public.refund_requests USING btree (user_id);


--
-- Name: idx_shipment_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_shipment_created_at ON public.shipments USING btree (created_at);


--
-- Name: idx_shipment_order_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_shipment_order_id ON public.shipments USING btree (order_id);


--
-- Name: idx_shipment_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_shipment_status ON public.shipments USING btree (status);


--
-- Name: idx_shipment_tracking_no; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_shipment_tracking_no ON public.shipments USING btree (tracking_no);


--
-- Name: idx_sizes_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sizes_code ON public.sizes USING btree (code);


--
-- Name: idx_tracking_event_event_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tracking_event_event_time ON public.tracking_events USING btree (event_time);


--
-- Name: idx_tracking_event_shipment_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tracking_event_shipment_id ON public.tracking_events USING btree (shipment_id);


--
-- Name: idx_user_measurements_bmi; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_measurements_bmi ON public.user_measurements USING btree (bmi);


--
-- Name: idx_user_measurements_gender_bmi; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_measurements_gender_bmi ON public.user_measurements USING btree (gender, bmi);


--
-- Name: idx_user_measurements_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_measurements_user_id ON public.user_measurements USING btree (user_id);


--
-- Name: idx_voucher_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_voucher_active ON public.vouchers USING btree (is_active);


--
-- Name: idx_voucher_rank_rule_rank_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_voucher_rank_rule_rank_id ON public.voucher_rank_rules USING btree (rank_id);


--
-- Name: idx_voucher_rank_rule_voucher_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_voucher_rank_rule_voucher_id ON public.voucher_rank_rules USING btree (voucher_id);


--
-- Name: idx_voucher_start_end; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_voucher_start_end ON public.vouchers USING btree (start_at, end_at);


--
-- Name: idx_voucher_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_voucher_type ON public.vouchers USING btree (type);


--
-- Name: idx_voucher_usage_order_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_voucher_usage_order_id ON public.voucher_usages USING btree (order_id);


--
-- Name: idx_voucher_usage_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_voucher_usage_status ON public.voucher_usages USING btree (status);


--
-- Name: idx_voucher_usage_used_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_voucher_usage_used_at ON public.voucher_usages USING btree (used_at);


--
-- Name: idx_voucher_usage_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_voucher_usage_user_id ON public.voucher_usages USING btree (user_id);


--
-- Name: idx_voucher_usage_voucher_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_voucher_usage_voucher_id ON public.voucher_usages USING btree (voucher_id);


--
-- Name: spring_ai_vector_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX spring_ai_vector_index ON public.vector_store USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: addresses fk1fa36y2oqhao3wgg2rw1pi459; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT fk1fa36y2oqhao3wgg2rw1pi459 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: product_images fk1j9bvqvvdudsd1ydm4fr0y3bk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fk1j9bvqvvdudsd1ydm4fr0y3bk FOREIGN KEY (image_id) REFERENCES public.images(id);


--
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: wishlists fk330pyw2el06fn5g28ypyljt16; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT fk330pyw2el06fn5g28ypyljt16 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: interactions fk3en1u622jlvp97u4p5q93qyom; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interactions
    ADD CONSTRAINT fk3en1u622jlvp97u4p5q93qyom FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: refund_requests fk452xm7hwgngbanwkdgs3601b1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT fk452xm7hwgngbanwkdgs3601b1 FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: product_details fk5tcr8s5m0i3prlty9w0crocog; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_details
    ADD CONSTRAINT fk5tcr8s5m0i3prlty9w0crocog FOREIGN KEY (color_id) REFERENCES public.colors(id);


--
-- Name: payments fk81gagumt0r8y3rmudcgpbk42l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: interactions fk8obf6rb85m8hmi3phq2qnm204; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interactions
    ADD CONSTRAINT fk8obf6rb85m8hmi3phq2qnm204 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: refund_images fk8qi1m89r8vyp4dec8595cfx0g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_images
    ADD CONSTRAINT fk8qi1m89r8vyp4dec8595cfx0g FOREIGN KEY (refund_request_id) REFERENCES public.refund_requests(id);


--
-- Name: cart_details fk_cart_detail; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_details
    ADD CONSTRAINT fk_cart_detail FOREIGN KEY (detail_id) REFERENCES public.product_details(id);


--
-- Name: cart_details fk_cart_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_details
    ADD CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: orders fk_order_voucher; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_order_voucher FOREIGN KEY (voucher_id) REFERENCES public.vouchers(id);


--
-- Name: password_reset_token fk_password_reset_token_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT fk_password_reset_token_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: refresh_tokens fk_refresh_token_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_roles fk_user_role_role; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles fk_user_role_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: voucher_rank_rules fk_voucher_rank_rule_rank; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_rank_rules
    ADD CONSTRAINT fk_voucher_rank_rule_rank FOREIGN KEY (rank_id) REFERENCES public.user_ranks(id);


--
-- Name: voucher_rank_rules fk_voucher_rank_rule_voucher; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_rank_rules
    ADD CONSTRAINT fk_voucher_rank_rule_voucher FOREIGN KEY (voucher_id) REFERENCES public.vouchers(id);


--
-- Name: voucher_usages fk_voucher_usage_order; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_usages
    ADD CONSTRAINT fk_voucher_usage_order FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: voucher_usages fk_voucher_usage_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_usages
    ADD CONSTRAINT fk_voucher_usage_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: voucher_usages fk_voucher_usage_voucher; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_usages
    ADD CONSTRAINT fk_voucher_usage_voucher FOREIGN KEY (voucher_id) REFERENCES public.vouchers(id);


--
-- Name: reviews fka6fy7npl2qi9nu2fo9igepm9k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fka6fy7npl2qi9nu2fo9igepm9k FOREIGN KEY (order_detail_id) REFERENCES public.order_details(id);


--
-- Name: promotion_targets fkadouvnh81yd8a64bk7wn435je; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promotion_targets
    ADD CONSTRAINT fkadouvnh81yd8a64bk7wn435je FOREIGN KEY (promotion_id) REFERENCES public.promotions(id);


--
-- Name: product_details fkccs28awcbxp3s7mjthrwcdwvn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_details
    ADD CONSTRAINT fkccs28awcbxp3s7mjthrwcdwvn FOREIGN KEY (size_id) REFERENCES public.sizes(id);


--
-- Name: reviews fkcgy7qjc1r99dp117y9en6lxye; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkcgy7qjc1r99dp117y9en6lxye FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: product_categories fkd112rx0alycddsms029iifrih; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT fkd112rx0alycddsms029iifrih FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: reviews fkdii2jr3liylnwp5l6xowl2qyk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkdii2jr3liylnwp5l6xowl2qyk FOREIGN KEY (product_detail_id) REFERENCES public.product_details(id);


--
-- Name: tracking_events fkejyddin0ap6h36fq9fuhoq8lp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tracking_events
    ADD CONSTRAINT fkejyddin0ap6h36fq9fuhoq8lp FOREIGN KEY (shipment_id) REFERENCES public.shipments(id);


--
-- Name: refund_requests fkh2s2m4dt9mnx896s9uccsguib; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT fkh2s2m4dt9mnx896s9uccsguib FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: product_images fki5siogidlj9shrs4d8feh0g64; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fki5siogidlj9shrs4d8feh0g64 FOREIGN KEY (detail_id) REFERENCES public.product_details(id);


--
-- Name: order_details fkifxxlr4oonxuwby9pn0ow32gy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT fkifxxlr4oonxuwby9pn0ow32gy FOREIGN KEY (detail_id) REFERENCES public.product_details(id);


--
-- Name: order_detail_promotions fkijlyinba14qa7gvxypneqkouj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_detail_promotions
    ADD CONSTRAINT fkijlyinba14qa7gvxypneqkouj FOREIGN KEY (promotion_id) REFERENCES public.promotions(id);


--
-- Name: order_details fkjyu2qbqt8gnvno9oe9j2s2ldk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT fkjyu2qbqt8gnvno9oe9j2s2ldk FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: user_measurements fkkmrgsg7fmw73wop8m6e6gh5ll; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_measurements
    ADD CONSTRAINT fkkmrgsg7fmw73wop8m6e6gh5ll FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: product_categories fklda9rad6s180ha3dl1ncsp8n7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT fklda9rad6s180ha3dl1ncsp8n7 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: order_detail_promotions fklqg0ncoio5q9f657yfpjjtdk4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_detail_promotions
    ADD CONSTRAINT fklqg0ncoio5q9f657yfpjjtdk4 FOREIGN KEY (detail_id) REFERENCES public.product_details(id);


--
-- Name: orders fkmk6q95x8ffidq82wlqjaq7sqc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkmk6q95x8ffidq82wlqjaq7sqc FOREIGN KEY (shipping_address_id) REFERENCES public.addresses(id);


--
-- Name: product_details fknfvvq3meg4ha3u1bju9k4is3r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_details
    ADD CONSTRAINT fknfvvq3meg4ha3u1bju9k4is3r FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: order_detail_promotions fkr91odesj6i5sd744r7dt59wou; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_detail_promotions
    ADD CONSTRAINT fkr91odesj6i5sd744r7dt59wou FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: refund_images fkrdblkjtraf0b872neydr4tlob; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_images
    ADD CONSTRAINT fkrdblkjtraf0b872neydr4tlob FOREIGN KEY (image_id) REFERENCES public.images(id);


--
-- Name: shipments fkrnt4wht95lxxplspltrg9681s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT fkrnt4wht95lxxplspltrg9681s FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: categories fksaok720gsu4u2wrgbk10b5n8d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fksaok720gsu4u2wrgbk10b5n8d FOREIGN KEY (parent_id) REFERENCES public.categories(id);


--
-- Name: refund_requests fktb7q1vrl41ymawdrp0cj9i3p9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT fktb7q1vrl41ymawdrp0cj9i3p9 FOREIGN KEY (processed_by) REFERENCES public.users(id);


--
-- Name: wishlists fktg8rqo8d22yktj5r0vyu6ejie; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT fktg8rqo8d22yktj5r0vyu6ejie FOREIGN KEY (detail_id) REFERENCES public.product_details(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

